development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://bgpylqdnfpdwml:e87e9dccdb22cad73e4acbe31b2f3fbc637be64f764243c601c81aca2f85cf27@ec2-23-23-235-86.compute-1.amazonaws.com:5432/d9v5llv7e3l5ci 
  #url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: webshop_production
